### PR TITLE
Hotfix for issue #590

### PR DESCRIPTION
**Pull request by izotos**
Possible fix for #590

### CODE REVIEW

**Comment by johman10** [comment]
I confirm that this fixes the issue mentioned in #590. Is there any chance this will get merged?

**Comment by peterswimm** [comment]
Has anyone been able to confirm it does not BREAK other aspects of the Slack integration?

**Comment by erodewald** [comment]
Happy to help verify as well @peterswimm, just not sure what specifically. We're using this PR internally for a slash command exclusively with no issues.

**Comment by izotos** [comment]
@peterswimm I can also confirm this works for us as well, though we only use it in our development env. Also unsure what I should be testing, I can just list the things that _do_ work in our applications:
 - API calls (`bot.api.`)
 - Interactive messages (`replyInteractive`, `replyInThread`)
 - Dialog (`replyWithDialog`) _which fails in current version_

**Comment by ryansydnor** [comment]
This is handled more comprehensively by https://github.com/howdyai/botkit/pull/1453. Closing in favor of that PR.

**Pull request closed without merging**
