### PR TITLE
Replace consoleLogger and log solutions with debug

### PR DESCRIPTION
**Pull request by anonrig**
The main purpose of this pull request is to change the logging mechanism from scratch.

`DEBUG=* npm start` will log all of the components to the terminal with different colors.

Example:

screen shot 2016-06-03 at 9 53 01 pm

PS: Have to bump version in order to accept this PR.

### CODE REVIEW

**Comment by rafaelamorim** [comment]
+1 on this!
you rock man!

**Comment by derrickpelletier** [comment]
Would like to see this instead of the logging built in, but wouldn't it make more sense to have the debug tokens be prepended with something unique to botkit? `botkit:core:bot:debug`?

Just so when using the lib with other `debug`able libs you have the ability to switch. Express for example is prepended with `express:*`, socket.io, nodemon, etc., all do the same.

... or is this PR abandoned in favour of something else that came afterward.

**Comment by anonrig** [comment]
You're right @derrickpelletier 👍 

This is an abandoned PR because none of the other contributors seemed interested on the topic of changing something that's been used in a very long time.

**Comment by benbrown** [comment]
I'd love to re-address this later. The logging is very inconsistent and not great!

**Pull request closed without merging**
