### PR TITLE
Add option to disable default startup message

### PR DESCRIPTION
**Pull request by JoshuaKlassen**
This PR is to add the option to disable the `Initializing Botkit vXXX` message as per #687 

To achieve this, `CoreBot.js` was modified to check for `disable_startup_message` on the configuration object.
If `disable_startup_message=true`, the startup message will not be shown.

Example:
```
var controller = Botkit.slackbot({
    debug: true,
    disable_startup_message: true
});
```

<s>Upon getting started, I noticed that `.vscode` files are not in the `.gitignore` (I am using VSCode)
If this is intentional let me know and I can undo the change.</s>
My VSCode editor generated a `settings.json` file, I have added that to the `.gitignore` incase this is something that should be ignored - if not it can be removed.

### CODE REVIEW

**Comment by jonchurch** [comment]
I'd suggest changing it from a `console.log` to a `botkit.debug` instead of adding a new config option to the growing list.

**Comment by JoshuaKlassen** [comment]
Sounds good, I'll make the change to `botkit.debug`

As for the starter kits, would that be acceptable to make debug enabled by default?

**Comment by peterswimm** [comment]
Could you explain why setting debug to being on default is preferred behaviour? My gut is that it would be an annoyance for most first time users, and is only really useful for people diagnosing unusual problems.

The initializing message is useful for us, particularly with regards to roadmap plans and supporting problems, and will eventually contain other useful information for developers. but being able to opt-out of receiving them is probably a reasonable request.

**Comment by JoshuaKlassen** [comment]
I just did what @jonchurch suggested, I have no preference

**Comment by benbrown** [comment]
I like @JoshuaKlassen's original idea - allow the message to be disabled independently of debugging.  I believe this IS important to be on by default.

**Comment by JoshuaKlassen** [comment]
I reverted back to original idea. I also felt it would be appropriate to make the config option plural, seeing as how we could add more startup messages in the future

**Comment by jonchurch** [comment]
👍 Sounds good to me. 

@peterswimm I agree, that would likely annoy developers. I was suggesting a scenario where the startup is on by default, but dependent on debug mode. 

Y'alls solution is cleaner and more predictable though.

**Comment by JoshuaKlassen** [comment]
@peterswimm, @jonchurch, @benbrown: is there anything I am missing, or is this good to go?

**Pull request merged**
