### PR TITLE
FB require_delivery: Remove use of message.delivery.mids because not guaranteed

### LINKED ISSUE #1311: `require_delivery` sometimes fails on Facebook
We [currently](https://github.com/howdyai/botkit/blob/9a876e6dc2686117b3cdc7fb1e6f6ed74e0d9dd0/lib/Facebook.js#L515) assume that `message.delivery.mids` always exists. This is not always the case, as specified in [Facebook's docs](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-deliveries):

**Property** | **Type** | **Description**
--------------|----------------|-----------------
   `mids`    |     Array     | Array containing message IDs of messages that were delivered. *Field may not be present.*

(italics mine)

In terms of a fix, what do you think of iterating through all messages and marking as "delivered" the ones after the given "watermark" date?

### PR DESCRIPTION
**Pull request by cchan**
Fixes #1311

### CODE REVIEW

**Comment by benbrown** [comment]
@cchan can you help me understand how to test this?

**Comment by cchan** [comment]
@benbrown That's an interesting question; I'm not sure how testing works for botkit. Do you have mocks set up for Facebook?

**Comment by cchan** [comment]
(oops)

**Comment by cchan** [comment]
@benbrown Hm, could we create a sinon test similar to [this existing one](https://github.com/howdyai/botkit/blob/master/tests/Facebook.js#L165)? I'm not familiar at all with how botkit works internally, but it seems like there's a polling loop that checks if the previous message has been marked as delivered before sending the next one.

**Comment by benbrown** [comment]
@cchan my original comment probably confused the issue. what I need to know is what settings to enable  and what type of events I need to trigger in order to see this fix in action.

**Comment by cchan** [comment]
@benbrown Ah, that's what you mean. You just need to set `require_delivery: true` and send a bunch of messages in a row from Botkit - that's pretty much it. Facebook will respond with delivery events, but once in a while the response will not contain the field `mids`, which crashes the old code.

I haven't been able to figure out what conditions cause Facebook to not provide `mids` in the response, but after you try it for enough times / long enough it'll just happen, seemingly at random. I think it's probably a load reduction feature on Facebook's end - the "delivered" feature is probably fundamentally based on the `watermark` timestamp, and when they don't have the capacity to generate the corresponding list of message IDs, they simply don't.

(The reason I found this bug is that I have a bot on my server (`clive-io/statbot`) that monitors logs et cetera, and it was crashing at random about once a week.)

**Comment by RJiryes** [comment]
Hey is this going to be merged anytime soon? Great catch @cchan ;-)

**Comment by benbrown** [comment]
@cchan @RJiryes merged!

**Comment by cchan** [comment]
Awesome! :D

**Comment by RJiryes** [comment]
@benbrown Thanks!

**Pull request merged**
