### PR TITLE
Socket.io bot

### PR DESCRIPTION
**Pull request by JacerOmri**
Basic socket.io implementation with express.

## Configuration
- address (optional)
- port (optional)

## Notes
- Tags user and channel with socket id.
- event for incoming messages is "incoming", bot messages are on "message". So basically the client would emit a message with "incoming" and listens to "message" to get a reply.

## Todos
- [x] basic implementation
- [x] some configuration
- [ ] use socketio rooms as channels
- [ ] a way to remember users
- [ ] a more sofisticated way of using socketio events
- [ ] documentation

### CODE REVIEW

**Comment by peterswimm** [comment]
@JacerOmri Are you still working on this?

**Comment by JacerOmri** [comment]
@peterswimm i'm waiting for any kind of feedback before making other changes.

**Comment by peterswimm** [comment]
What kind of feedback will help you move forward? I'd love to see this completed, but am not a Socket.io user myself.

**Comment by benbrown** [comment]
This PR is superseded by https://github.com/howdyai/botkit/projects/5

@jacerOmri would love your input!

**Pull request closed without merging**
