### PR TITLE
Added linter & editorconfig

### PR DESCRIPTION
**Pull request by anonrig**
It is really hard to both contribute and read the code clearly. Therefore, I've added editorconfig and linter files.

  - Editorconfig helps new contributors with the tab character and changes it with spaces. 4 for all files, 2 for json files. It helps indentation in general.
  - Modern text editors all have linter plugins for JavaScript including Atom, Webstorm etc. On top of Google's linter rules, I've made some adjustments to create a more unified code.

Hope you all like it.

### CODE REVIEW

**Comment by RafaelCosman** [comment]
Looks great! Thanks for making those, @anonrig. Have you also applied those rules to the existing codebase?

**Comment by anonrig** [comment]
Not really, I thought  I will work on it after the merge. Will solve it in 1 hour after

**Comment by anonrig** [comment]
@RafaelCosman Changed slackbot worker with new styling.

**Comment by RafaelCosman** [comment]
@anonrig Just tested ```demo_bot.js``` and it works. I'm going to merge this!

**Pull request merged**
