### PR TITLE
Added simple sentiment analysis example using AFINN list from sentime…

### PR DESCRIPTION
**Pull request by jamesdwilson**
…nt module.

### CODE REVIEW

**Comment by anonrig** [comment]
Mongo connection happens async as same as botkit spawn functionality. Therefore, race condition may occur if the `hears` method runs faster than mongo connection establishment. Please fix it.

**Comment by jamesdwilson** [comment]
Good call, will do.
This is my first bot. Thanks.

On Sat, Feb 27, 2016 at 5:56 AM, anonrig <notifications@github.com> wrote:

> Mongo connection happens async as same as botkit spawn functionality.
> Therefore, race condition may occur if the hears method runs faster than
> mongo connection establishment. Please fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/howdyai/botkit/pull/135#issuecomment-189622317>.
>



-- 
Thank you,

James D. Wilson
http://jameswilson.name
http://lnked.in/technologist
https://github.com/jamesdwilson
*https://twitter.com/thejamesdwilson <https://twitter.com/thejamesdwilson>*

**Comment by anonrig** [comment]
One more idea for your bot:

Sometimes functional programming isn't always the best method for a task due to decrease in readability and maintainability. Instead of doing such functions, I suggest using promises, and promisify some tasks you have. But anyways, good call.

**Comment by jamesdwilson** [comment]
I agree actually, but I wanted to keep this simple and allow the most
people possible to understand and make use of it.
My original code was in es2015.
I wish the whole repo was in es2015.


On Sat, Feb 27, 2016 at 4:17 PM, anonrig <notifications@github.com> wrote:

> One more idea for your bot:
>
> Sometimes functional programming isn't always the best method for a task
> due to decrease in readability and maintainability. Instead of doing such
> functions, I suggest using promises, and promisify some tasks you have. But
> anyways, good call.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/howdyai/botkit/pull/135#issuecomment-189738550>.
>



-- 
Thank you,

James D. Wilson
http://jameswilson.name
http://lnked.in/technologist
https://github.com/jamesdwilson
*https://twitter.com/thejamesdwilson <https://twitter.com/thejamesdwilson>*

**Pull request merged**
