### PR TITLE
Added delay capability to message.

### PR DESCRIPTION
**Pull request by tkornblit**
This will solve out of order messages for FB.

### CODE REVIEW

**Comment by Raniazy** [comment]
+1

**Comment by anonrig** [comment]
Can you solve the conflicts in `lib/CoreBot.js`?

**Comment by benbrown** [comment]
@tkornblit Can you explain to me a bit more why this is necessary?

There is already a facility for specifying a delay for each message that is relative to when the _previous message_ was sent.   This new code looks like it conflicts with that functionality...

**Comment by benbrown** [comment]
We've solved this issue by adding support for message delivery confirmation in the latest version.

**Pull request closed without merging**
