### PR TITLE
Baseline for unit testing

### PR DESCRIPTION
**Pull request by colestrode**
My goal is to write true unit tests that isolate components from each other (see #835 for more discussion). For this PR I hit 100% coverage on all statements/branches/functions/lines for the files I wrote tests for (run `npm test` to see the coverage report).

For now I just covered the main `Botkit.js` entry point and `Slack_web_api.js` since they were relatively small and I know them well. If this PR looks good, I can start adding more tests, file by file.

I chose Jest because of the great CLI and its speed. It also reduces the number of additional tools to know before writing tests (jest replaces my usual stack of mocha, chai, sinon, chai-sinon, and proxyquire).

I updated/added some npm scripts:

To run linting and tests: `npm test`
To run tests in watch mode: `npm run test-watch` (great for during development)
To run existing mocha/should integration tests (these will be deprecated once tests are backfilled): `npm run test-legacy`
NOTE: Linting now runs with --fix to fix common mistakes.

### CODE REVIEW

**Comment by colestrode** [comment]
BTW, I wrote these using ES6. We've talked a bit in the [Slack channel](https://dev4slack.slack.com/archives/C57S6LLS0/p1495226452685821) about beginning to incorporate ES6 features into Botkit over time. Tests seem like a good place to start with this, since they won't affect anyone's runtime experience.

Once we have good test coverage, we can start running tests in Travis (for example) against multiple Node versions to make sure that Botkit will run in all supported Node versions. At that point we can start pulling in more ES6 into the main project. I'll file an issue later for the community to discuss ES6 more fully.

**Comment by amplicity** [comment]
@colestrode and I talked about possible overlappage between this and botkit-mock..

Earlier, @benbrown and I had discussed using [botkit-mock](http://www.github.com/gratifyguy/botkit-mock) to unit-test core functionality. We currently mock functions like `callApi`, but both @ihorrusinko and I feel that cole's solution is better for unit testing botkit (ie low-level slack api), while botkit-mock is better for integration testing a botkit _instance_.

**Comment by benbrown** [comment]
@amplicity thanks for your feedback!

**Comment by benbrown** [comment]
BIG STEP FORWARD! Thanks @colestrode!

**Pull request merged**
