### PR TITLE
[Sockets] dont set guid

### PR DESCRIPTION
**Pull request by Naktibalda**
It is a responsibility of the client side code to generate guid.
Fixes https://github.com/howdyai/botkit-starter-web/issues/10
Comes in pair with https://github.com/howdyai/botkit-starter-web/pull/11

### CODE REVIEW

**Comment by gagan-bansal** [comment]
I too changed the guid generation at client side. But one doubt why have you removed triggering of `message.type`. It helps at backend to do something when user connects first time like loading user profile. 
So I feel setting up guid can be part of client  and retain triggering of initial connection ('hello') and reconnect.

**Comment by Naktibalda** [comment]
> But one doubt why have you removed triggering of message.type.

I haven't removed `controller.trigger(message.type, [bot, message]);`, it still present in the else block.

**Comment by gagan-bansal** [comment]
Oh yes, I missed it, sorry for bothering you.

**Comment by Naktibalda** [comment]
@benbrown I rebased this branch to resolve merge conflict with your pipeline change.

**Pull request merged**
