### PR TITLE
Add support for SMS via Twilio Programmable SMS API (work in progress)

### PR DESCRIPTION
**Pull request by krismuniz**
Howdy, Botkit team! :wave:

I wrote this Botkit SMS implementation and [published it on `npm`](https://www.npmjs.com/package/botkit-sms) a while ago but never managed to submit a PR to include it in the main Botkit project. 

I modified it to match the project's source code style (checked using `jscs`), included it in `botkit`'s main export, and added an example bot.

Of course, this is a working draft. If you have any feedback, let me know :eyes:

### :memo: Task List

- [x] Write main platform implementation (`./lib/TwilioSMSBot.js`)
- [x] Include platform implementation into core `botkit` export
- [x] Write API documentation and guide for bot developers
- [x] Write an example bot (`./twilio_sms_bot.js`, derived from `./twilio_ipm_bot.js`)

## PR Summary

This PR enables Botkit users to build SMS bots using [Twilio's Programmable SMS API](https://www.twilio.com/sms). This submission is for preliminary code review.

### Implementation

Similar to the Facebook Messenger implementation, Twilio Programmable SMS API sends webhooks to an arbitrary URI when SMS' are received. 

This implementation consists of mounting `express` middleware to listen for these events on an arbitrary `endpoint` (`/sms/receive`, by default) and passing it as an argument of `Bot#receiveMessage(bot, message)` To send messages, on the other hand, it uses the `twilio` package (which already comes installed in Botkit) to construct and send TWIML requests to the Twilio API.

These patterns are similar to the ones used on `./lib/Facebook.js` to support Messenger Platform.

## Example Usage

TwilioSMSBot works pretty much as a regular Botkit user would expect. Given the simplistic nature of SMS, it can be really easy to get used to developing SMS bots with Botkit.

```js
/* Minimal SMS bot powered by Twilio Programmable SMS and Botkit */
const TwilioSMSBot = require('botkit').twiliosmsbot

const controller = TwilioSMSBot({
  account_sid: process.env.TWILIO_ACCOUNT_SID,
  auth_token: process.env.TWILIO_AUTH_TOKEN,
  twilio_number: process.env.TWILIO_NUMBER
})

let bot = controller.spawn({})

controller.setupWebserver(process.env.PORT, function (err, webserver) {
  if (err) console.log(err)

  controller.createWebhookEndpoints(controller.webserver, bot, function () {
    console.log('TwilioSMSBot is online!')
  })
})

controller.hears(['hi', 'hello'], 'message_received', (bot, message) => {
  bot.startConversation(message, (err, convo) => {
    if (convo) console.log(err)

    convo.say('Hi, I am Oliver, an SMS bot! :D')
    convo.ask('What is your name?', (res, convo) => {
      convo.say(`Nice to meet you, ${res.text}!`)
      convo.next()
    })
  })
})

controller.hears('.*', 'message_received', (bot, message) => {
  bot.reply(message, 'huh?')
})
```

### CODE REVIEW

**Comment by benbrown** [comment]
Hey @krismuniz how goes this effort? We're thinking about some other SMS-related things, and want to make sure we don't duplicate effort!

**Comment by krismuniz** [comment]
I'll work on this in the following days! :) It's fully functional, but there's still work that needs to be done. Like testing and docs/guides for fellow botkit developers.

Feel free to review my work so far.
________________________________

**Comment by krismuniz** [comment]
Hello @benbrown, @peterswimm  the only thing left is to write tests. Is there a consistent way to test Botkit platform implementations? The tests that are already in the project are a bit different from one another.

**Comment by benbrown** [comment]
@krismuniz I think the best method right now is to use `botkit-mock` to test.

**Comment by bilby91** [comment]
Any updates on this ? We are starting a new bot that will definitely improve if we have support for Twilio SMS.

**Comment by peterswimm** [comment]
@bilby91 This is quite usable as is, we hope to get this merged into the core project asap!

**Comment by bilby91** [comment]
@peterswimm Just for curiosity, how is the state of the conversation handled in SMS ? Does Twilio provide something for having SMS conversations or this is done using timeouts ? Like, if user reply is < last SMS sent + timeout it means is replying to the conversation and not starting a new one ?

Maybe this is a stupid question but wanted to ask it :)

**Comment by peterswimm** [comment]
Conversations have a default 15 minute timeout, we dont automatically create sessions, so youd have to add this if you want to change these defaults. @bilby91

**Comment by bilby91** [comment]
@peterswimm Thanks for the reply! Yesterday I spent some time digging in the Botkit code and figure out that what I wanted was not possible. What this also implies is that Botkit can not be used in a multi-server setup if you want to use the conversations api right ?

**Comment by peterswimm** [comment]
We can and do use Botkit in a multi-server setup with Howdy, you just need to keep track of user conversations and sessions in your storage and in your code. We have plans to document this more fully in a future update.

**Comment by bilby91** [comment]
Awesome!

Martín Fernández

On Tue, Jun 27, 2017 at 18:12 Peter Swimm

<
mailto:Peter Swimm <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

We can and do use Botkit in a multi-server setup with Howdy, you just need to keep track of user conversations and sessions in your storage and in your code. We have plans to document this more fully in a future update.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/howdyai/botkit/pull/734#issuecomment-311486958
, or

**Pull request merged**
