### PR TITLE
Added support for Facebook "attachment" type of objects for conversat…

### PR DESCRIPTION
**Pull request by tkornblit**
…ions.

### CODE REVIEW

**Comment by crummy** [comment]
Works great for me, thanks - just what I was looking for.

BTW, I had to add lodash to `package.json` to build it.

**Comment by tkornblit** [comment]
Cool brother. What are you working on?
--
Tom Kornblit

**Comment by crummy** [comment]
Experimenting with an interactive resume bot for my girlfriend. Images were a must :)

**Comment by crummy** [comment]
One thing I noticed is that image messages sometimes arrive out of order with text messages. Not sure why, perhaps that's a facebook issue. I'm considering increasing the delay between messages to help.

**Comment by tkornblit** [comment]
Use botkits Conversation class. It has a built-in queue mechanism.
--
Tom Kornblit

**Comment by benbrown** [comment]
@tkornblit thanks for the PR. I'm merging in the attachment related features here, but not sure about the changes you've made to the findConvo and others. Maybe open a new PR if you want to get that stuff included?

**Pull request closed without merging**
