### PR TITLE
Make custom auth available to the user of the OAuth endpoint.

### PR DESCRIPTION
**Pull request by shishirsharma**
Slack now has a full identity scope with things like email, avatar. These are
not available via req.identity

### CODE REVIEW

**Comment by shishirsharma** [comment]
Also providing auth lets users handle a lot of edge cases in auth flow gracefully.

**Comment by benbrown** [comment]
@shishirsharma Can you please add a note about this change to the appropriate readme file? After that, I can merge it in!

**Comment by shishirsharma** [comment]
@benbrown Done, You can now merge.

**Comment by benbrown** [comment]
Thanks!

**Comment by shishirsharma** [comment]
Do let me know If you guys need anything else too.

**Comment by shishirsharma** [comment]
Guys, I am bumping this up. Let me know what is stopping this from being merged. I am open for new/different strategies.

If there is no disagreement then please merge this asap. Merging will help us use mainstream botkit branch for development.

**Comment by shishirsharma** [comment]
@benbrown I fixed unnecessary merge.

**Comment by shishirsharma** [comment]
I believe this PR is moot in favour of the botkit-starter-slack approach. In starter kit approach complete oauth handling has been OP's responsibility not Botkit's. 

here is the relevant code.  https://github.com/howdyai/botkit-starter-slack/blob/master/components/routes/oauth.js 

I intend to close this tomorrow. Just in case someone has other opinion.

**Pull request closed without merging**
