### PR TITLE
Introduction of Platform Provisioning Documents

### PR DESCRIPTION
**Pull request by peterswimm**
We've put off having verbose documentation for platforms long enough, here is a crack at supporting detailed directions on provisioning bots for the platforms that Botkit supports. More on the way.

### CODE REVIEW

**Comment by anonrig** [comment]
Can you add this to .npmignore file? Since we don't want to install all of these images when we do `npm i botkit`.

**Comment by peterswimm** [comment]
@anonrig you could argue that a npm installer NEEDS these docs too. Do you propose we should opt out of everything BUT the readme.md, and have a TOC to the other docs only in that for NPM installers?

**Comment by colestrode** [comment]
I think @anonrig's makes a good point: this is quite a bit to download. I also think the main usefulness of including these images in an npm package would be offline access. But if I'm offline, I'm not going to be able to provision a bot 😄 

Also a large number (easily over 90%) of my installs are on CI servers, so this would be an increase in build time for no real gain.

**Comment by anonrig** [comment]
No body will ever read the docs when they install it from NPM. Again it's your choice, but this will increase the package size and do no good to the developer. @colestrode @peterswimm

**Comment by peterswimm** [comment]
Thanks for the feedback, my gut is to leave them in the project, but we will take your feedback under advisement.

**Comment by benbrown** [comment]
I am going to add an .npmignore file and exclude these images, but leave the docs.

This is my own personal bias, but I *do* occasionally open up node_modules to find the docs.

**Pull request merged**
