### PR TITLE
add middleware entry point to preprocess messages

### PR DESCRIPTION
**Pull request by mikehmorrissey**
@benbrown i've been using this in my fork of botkit and I think at lot of people would find it useful. it introduces a middleware layer before triggering the direct_message, ambient, direction_mention and mention events. This allows for message normalization/preprocessing. for example I could write something like this: 

```js
const normalize = (bot, message, next) => {
  message.text = message.text.replace('gonna', 'going to')
  next()
}

const BotController = Botkit.slackbot({
  // can be an array of functions
  middleware: normalize
})
```

that's a pretty simple example but i can imagine people writing middleware to normalize common typos, slang, contractions, etc. What do you think? I'll write up the documentation and provide a solid example if you're into it.

### CODE REVIEW

**Comment by RafaelCosman** [comment]
@mikehmorrissey this seems useful! I think it would be great to have a set of standard normalization functions that we could drop in. Let's reach out in dev4slack.slack.com and see if anyone's interested in collaborating on this. Also let's poll the level of interest in this feature. I know that I have at least one bot that should be using something like this.

**Comment by DEGoodmanWilson** [comment]
It would be nice—bear in mind I'm somewhat new to Node and Node idioms—if things were namespaces in such a way as to be able to add new middleware at different points in the flow. For example, I am wanting to add a middleware hook around local cacheing of channel/user/message objects.

**Comment by anonrig** [comment]
Instead of passing a variable to the constructor why don't we use ExpressJs' `app.use()` typing? It seems more understandable and may afford multiple middlewares at the same time. 

What do you think @mikehmorrissey ?

**Comment by benbrown** [comment]
Or both!

**Comment by mikehmorrissey** [comment]
@DEGoodmanWilson @anonrig @benbrown @RafaelCosman  thanks for the feedback! I definitely agree that it needs some naming work to allow for middleware in other parts of the event flow. Does anyone have a suggestion for this particular instance? I'm thinking ``preprocessor`` instead of ``middleware``. 

I think we can easily do both the constructor and the expressJS style. how i currently have it allows for setting middleware both ways. 

```js
const BotController = Botkit.slackbot({
  preprocessor: [normalize, unslang]
})

BotController.preprocessor.use(simplify)
```

**Comment by anonrig** [comment]
The naming `middleware` is more fit to this situation. I really liked this naming style.

```
BotController.use(simplify);
```

or

```
BotController.use(function(data) {} );
```

**Comment by benbrown** [comment]
@anonrig with the .use syntax, how do we tell Botkit at which point in the process the function should be fired?

**Comment by anonrig** [comment]
The function shouldn't be fired actually. We can use event driven programming and have an enum of events in the botkit code. With each specific function, we can fire that event with a compatible callback mechanism where a preprocessed function will have access to.

What do you guys think about it?

**Comment by RafaelCosman** [comment]
I'll leave this one to the experts. @benbrown, @mikehmorrissey?

**Comment by mikehmorrissey** [comment]
@anonrig not sure exactly what you are suggesting. I think my current implementation is pretty simple to use and understand. 

@benbrown @RafaelCosman I just saw an interesting module come out that would have fit perfectly as preprocessing middleware https://blog.beepboophq.com/natural-language-slackbots-with-wit-ai-and-beep-boop-c007cf303c04#.v1egcp1zk

**Comment by benbrown** [comment]
Still thinking about this! I plan on adding in some middleware hooks soon, but I am still researching the best way to do so.

**Comment by RafaelCosman** [comment]
@benbrown what are you thinking?

**Comment by colestrode** [comment]
I'd say if you're going to call them "middleware", which seems appropriate given @mikehmorrissey's first example, then I think will make the most sense to people using Express to do what @anonrig is suggesting. I would have messages pass through each middleware in the order it was registered. 

Whatever syntax you choose, I would suggest picking only one. Having two ways to support the same thing increases your complexity, docs, tests, etc.

**Comment by dcsan** [comment]
is this pattern also going to work for adapting output to various clients? eg Slack may need a message packaged in a different way than hipchat and that can be delegated to the right middleware?

I guess hubot uses the "adapter" pattern for this, but it wasn't flexible enough to support anything other than lowest common denominator see this issue:
https://github.com/github/hubot/issues/1036#issuecomment-178240267

**Comment by mikehmorrissey** [comment]
@benbrown feel free to close this. seems like you have a better approach on the middleware branch!

**Pull request closed without merging**
