### PR TITLE
Bug/#852 fixes an error when message.delivery.mids undefined

### PR DESCRIPTION
**Pull request by jsalwen**
fix for #852 bug

Code just set `deliveryMids` to value or `message.delivery.mids` or `[]`

### CODE REVIEW

**Comment by smalltalk-josh** [comment]
this fixes a error when `message.delivery.mids` undefined

**Comment by smalltalk-josh** [comment]
@benbrown any questions on this? this issue is a blocker for using ref codes for Facebook Messenger. Let me know if there is anything I can do to help move this forward.

**Comment by jsalwen** [comment]
@peterswimm anything I can do to help with this?  this bug is a blocker for using ref codes for Facebook Messenger. Let me know if there is anything I can do to help move this forward.

**Comment by jonchurch** [comment]
@jsalwen @smalltalk-josh This occurs when you are using delivery confirmation, and a referral message is sent to the server, correct?

The issue is that with all other messages, there is a mid field, whereas referral events do not come with a mid field, so an error is thrown. This PR fixes that by ensuring there is a value to iterate over.

Looks good to me @peterswimm @benbrown

**Comment by jsalwen** [comment]
@jonchurch you are 100% correct.
At the moment, when using botkit with delivery confirmation for facebook messenger, referrals are broken.
@peterswimm @benbrown any ETA on merge or feedback? I'm happy to change it. It is still a blocker.

**Comment by jsalwen** [comment]
@peterswimm @benbrown any update? minor change, but big impact, since it prevents the use of ref codes for Facebook Messenger

**Comment by benbrown** [comment]
Merging this into the next release!!

**Pull request merged**
