### PR TITLE
Add clear event method to controller.

### PR DESCRIPTION
**Pull request by colus001**
### Why
- There's no way to clear events

### What I did
- Add `.clear` to remove existing events.

### To do (maybe me?)
- Clear event by callback

### CODE REVIEW

**Comment by colus001** [comment]
I think it is necessary to change `.on(event, callback)` method to use some `id` so that it can be cleared by the reference.

**Comment by colestrode** [comment]
The Node EventEmitter API provides an `removeListener` method, which takes an event type and a reference to the event callback, that signature might be a more intuitive API for Node developers. There is also a `removeAllListeners` which just takes an event type and removes all handlers: 

* https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener
* https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname

**Comment by colus001** [comment]
@colestrode That would be better. I'll change it soon. :D

**Comment by jonchurch** [comment]
@colestrode any interest in picking this back up? I saw someone asking about this functionality recently

**Pull request closed without merging**
