### PR TITLE
Add functionality for typing in conversations

### PR DESCRIPTION
**Pull request by nischayv**
Issue - #674

This PR allows users to simulate typing in conversations, similar to what is being done with replyWithTyping. 
```
bot.startConversation(message, (err, convo) => {
        convo.askWithTyping('Are you sure?', [  {
                pattern: bot.utterances.no,
                default: true,
                callback: (response, convo) => {
                    convo.sayWithTyping('*Phew!*');
                    convo.next();
                }
            }
       ]);
});
```

I followed what was being done for replyWithTyping.

### CODE REVIEW

**Comment by devhaoy** [comment]
Hi @nischayv  I found several issues with your fix. 
1/ All convo.ask which `message` is not a string (buttons, quick_replies etc.) won't fire and give error `API ERROR { message: '(#100) Message cannot be empty, must provide valid attachment or text'`
2/ When sending attachment with convo.say, throw error `TypeError: Cannot read property 'length' of undefined`
3/ Sending emojis (with no text) messes up the whole convo. Probably a a shortcoming of the `length` property. Surprisingly, the emoji will be ignored and fired in the subsequent thread. This seems to confuse botkit, and eventually all the convo.say('text') are sent in the wrong order. 

@jonchurch  are you working on your own fix to simulate typing in convo?

**Comment by nischayv** [comment]
@devhaoy Thanks for pointing that out. I'll look into what's going wrong. By any chance do you know why that's happening? Any help would be appreciated. I'm new to botkit, and would really like to contribute to it.

**Comment by devhaoy** [comment]
@nischayv  I have little understanding of the Corebot mechanism, I'd rather not mislead you! As Jon Church pointed out it is some kind of hack to tweak `bot.replyWithTyping`  for use with convo, so I suppose `typing` needs to be an isolated argument dedicated to convo.

**Comment by jonchurch** [comment]
@devhaoy This is a different fix than the hack I proposed in #674 

I'm just switching out the bot.reply that is used to finally resolve sending a message in a convo (in CoreBot.js) with the existing bot.replyWithTyping, a function that is functionally the same as reply but wraps it with a user_typing call first. Mine will _definitely_ break if you are using a platform that doesnt have replyWithTyping implemented (like twilio, I believe).

I haven't started on a PR yet, but I was going to check a config variable on the controller to decide between using bot.reply or bot.replyWithTyping in CoreBot.js

**Comment by k001** [comment]
What is the differences between #724 and this?
Both wants the same behavior.

**Comment by nischayv** [comment]
@k001 The main difference seems the manner of usage. In my PR, we can do convo.replyWithTyping, which is similar to bot.replyWithTyping. In the other PR, it would have to be an added property with_typing. Given that both PR's did not account for platforms where typing is not available(twilio maybe), it may break things. I'll update my PR this weekend and make sure this feature is working.

**Comment by jonchurch** [comment]
@k001 The difference is that #724 will force all conversations to have typing on by default, within slack. 

This creates a new function which you can explicitly use instead of `convo.say()`

**Comment by c0nstructer** [comment]
@jonchurch what's the status with this merge and feature?

**Pull request closed without merging**
