### PR TITLE
Version 0.4.3

### PR DESCRIPTION
**Pull request by benbrown**
Facebook features!

Access to thread settings API
Improvements to reliabilty of sending
Better support for Facebook attachments with Botkit Studio

### CODE REVIEW

**Comment by devhaoy** [comment]
After updating to V.4.3, not receiving payload from Facebook buttons. Everything else working just fine, including the GetStarted payload, quick buttons (location). I can't find my way out of this, could you please advise?

```
welcome = function(response, convo) {
  convo.ask({
            attachment: {
                'type': 'template',
                'payload': {
                    'template_type': 'button',
                    'text': "Now what can I do for you?",
                    'buttons': [
                        {
                            'type': 'postback',
                            'title': 'aaa',
                            'payload': 'AAA',
                        },
                        {
                            'type': 'postback',
                            'title': 'bbb',
                            'payload': 'BBB',
                        },
                    ]  
                }
            }
        }, function(response, convo) { 
    convo.say("ok");
    switch(response.text) {
        case 'AAA':
        choiceA(response, convo);
        break;
        case 'BBB':
        choiceB(response, convo);
        break;
        default:
        info(response, convo);
    }
    convo.next();
  });
};
```

**Comment by benbrown** [comment]
@devhaoy so you're all set?

**Comment by devhaoy** [comment]
@benbrown yep it's all smooth now! Only spent a couple hours struggling to identify the issue

**Comment by benbrown** [comment]
Doh!! Sorry about that.

Are you part of the dev4slack.xoxco.com community? I try to broadcast breaking changes there.

**Comment by devhaoy** [comment]
Done! thanks for that

**Pull request merged**
