### PR TITLE
Clarify how to use localtunnel.me Facebook documentation

### PR DESCRIPTION
**Pull request by agamrafaeli**
This commit is meant to clarify how to use localtunnel.me for the facebook_bot. The problem arises in issue #457

### CODE REVIEW

**Comment by benbrown** [comment]
@agamrafaeli Thank you much for this!

This is however slightly incorrect.  The custom subdomain allows you to request your own *.localtunnel.me domain.  It is NOT the domain you get back automatically. 

Can you update the docs to reflect this?

**Comment by agamrafaeli** [comment]
@benbrown Done. Merge?

**Comment by benbrown** [comment]
These docs are still not quite right.

The purpose of the -s parameter is to request a specific subdomain. This is _instead of_ using the randomized subdomain that localtunnel provides by default.

**Comment by agamrafaeli** [comment]
@benbrown I simplified the explanation. If you don't like this one, can you give a short list of all of the things you would like included in this PR?

**Pull request closed without merging**
