### PR TITLE
Update slack_bot.js

### PR DESCRIPTION
**Pull request by cmkraus**

### CODE REVIEW

**Comment by benbrown** [comment]
@cmkraus did you just commit your own slack token?

what is your intent here? 

if this is a real token you should invalidate it immediately!

**Comment by cmkraus** [comment]
Hi, sorry new to all of this, very confused by your message. Could you explain a little more?

**Comment by benbrown** [comment]
@cmkraus the code you just submitted a pull request for includes your specific slack token.

this is now public, and will allow anyone who sees this pull request to access your slack team.

You should invalidate it immediately to avoid security problems.

**Comment by cmkraus** [comment]
@benbrown Thank you- how do invalidate a token? As I said very new to all of this!

**Pull request closed without merging**
