### PR TITLE
Formatting & Typo fixes

### PR DESCRIPTION
**Pull request by Xavdidtheshadow**
Noticed that some of the `botkit` headers weren't **aligned**, so I fixed that.

I also added shield.io **badges** for the most relevant information (npm version, dependency currentness

The `ws` vulnerability is described [here](https://nodesecurity.io/advisories/ws_buffer-leak) and should be patched, but I'll leave that to y'all.

### CODE REVIEW

**Comment by chrisbodhi** [comment]
Those gifs :raised_hands: 

Would it make sense to also remove `tap-spec` and `tape` from the [package.json](https://github.com/howdyai/botkit/blob/master/package.json#L18) in this PR? It looks like they're leftover from how the tests used to run, and not being used anymore.

**Comment by Xavdidtheshadow** [comment]
Good call! Also looks like `node-env-file` isn't being used either? The only place it shows up in the repo is in package.json itself. I'll pull all three.

**Comment by Xavdidtheshadow** [comment]
Also found these style errors after running `npm test`, fixed.

```
Invalid quote mark found at ./lib/CoreBot.js :
   358 |
   359 |                            if (message.text || message.attachments) {
   360 |                                message.text = message.text && this.replaceTokens(message.text) || "";
-----------------------------------------------------------------------------------------------------------^
   361 |                                if (this.messages.length && !message.handler) {
   362 |                                    message.continue_typing = true;

Operator != should not stick to preceding expression at ./lib/Slack_web_api.js :
    86 |            },
    87 |            postMessage: function(options, cb) {
    88 |                if (options.attachments && typeof(options.attachments)!='string') {
------------------------------------------------------------------------------^
    89 |                    options.attachments = JSON.stringify(options.attachments);
    90 |                }

Operator != should not stick to following expression at ./lib/Slack_web_api.js :
    86 |            },
    87 |            postMessage: function(options, cb) {
    88 |                if (options.attachments && typeof(options.attachments)!='string') {
--------------------------------------------------------------------------------^
    89 |                    options.attachments = JSON.stringify(options.attachments);
    90 |                }
```

**Comment by anonrig** [comment]
There are conflicts in this merge request. Please solve it :+1:

**Comment by Xavdidtheshadow** [comment]
@anonrig ah, sorry. Fixed!

**Comment by anonrig** [comment]
Security comes first. Can you update ws and before updating read the changelog and notify us if anything is broken?

Thank you.

**Comment by Xavdidtheshadow** [comment]
@anonrig the [commit](https://github.com/websockets/ws/commit/29293ed11b679e0366fa0f6bb9310b330dafd795) was a small one and after updating, all the tests and some tire-kicking passed.

**Comment by anonrig** [comment]
Thank you!

**Pull request merged**
