### PR TITLE
Properly handling Facebook attachements (Iimage + audio and video)

### PR DESCRIPTION
**Pull request by ouadie-lahdioui**
Hello guys,

I want to share with you how i handle an image, a video or an audio received by the bot.

Facebook support multiple types multimedia and templates attachments (image, audio, video), when the bot user is supposed to type a simple text but they send an image instead, Facebook provide an  attachements key in JSON sent by it and let text one empty.

what do you think ?

### CODE REVIEW

**Comment by jonchurch** [comment]
Looks good!

I think users can only send one attachment per message currently, and as long as thats true then triggering one per present attachment is fine. 

If fb introduced group chats with multi bots, we wouldnt want to trigger one per attachment.

**Comment by devhaoy** [comment]
Works perfectly but it seems to preempt any image received inside a convo. Some might prefer to handle attachment in their app.js to avoid this.

**Comment by benbrown** [comment]
I have something like this built into the Facebook starter kit. I share @devhaoy's concern that this could impact the ability to receive media inside conversations...

Should this be built into Botkit, or be something noted in the docs and included in the example apps?

**Comment by ouadie-lahdioui** [comment]
I'll take this into consideration on my Botkit fork, @benbrown i just whant to share with you how i do that and get a feedback !

**Pull request closed without merging**
