### PR TITLE
Facebook echoes and read receipts

### PR DESCRIPTION
**Pull request by arunthampi**

### CODE REVIEW

**Comment by malhotraa** [comment]
Looks good to me! Thanks @arunthampi.

**Comment by arunthampi** [comment]
@peterswimm / botkit team -- any updates on when we can get this merged? Thanks! <3

**Comment by peterswimm** [comment]
@arunthampi working on a big update of our own before Talkabot, once this push is released we should circle back around to reviewing some of the PR backlog. If time permits we will review as many of the smaller PRs we can and include them in the next update.

**Comment by benbrown** [comment]
Thanks, @arunthampi!

**Pull request merged**
